Support view transitions for dark mode toggle
markteekman/accessible-astro-components pull request #60
Opened 2023-10-09 19:08 UTC by david-abell

I've been playing around with the new [Sanity/Astro integration](https://www.sanity.io/plugins/sanity-astro#:~:text=complete%20implementation%20examples.-,Embedding%20Sanity%20Studio%20on%20a%20route,-Sanity%20Studio%20is) and the very cool new Astro 3 [viewTransitions api](https://docs.astro.build/en/guides/view-transitions/#full-site-view-transitions-spa-mode) that allows embeding a SPA inside a route.  

I noticed while doing so that the DarkMode toggle is broken with the new api.

 - Adding the `transition:persist` attribute to the top level `<button>` element keeps the variables and event listeners from disappearing. Incidentally this seems to also to be necessary for the accessible-astro-starter `has-dropdown` script logic...

 - `document.addEventListener('astro:after-swap', () => {}` runs after a page transition seems to be necessary to keep the `matchMedia('(prefers-color-scheme: dark)')` logic synced up.

Also, sorry for the major reformat on this one. Prettier seems to want to format inline scripts differently and for some reason that never happened before...I probably forgot the --write option when running `prettier .`  to format everything way back when :grimacing:.

2023-10-14 11:22 UTC, markteekman commented
Nice work @david-abell! This certainly enhances and future proofs these components even more, especially when working with those View Transitions 😊 I'll go through it right away!

2023-10-14 11:28 UTC, markteekman requested changes
This isn't really part of your changes but could you remove the `height: 100%` on this `.modal__inner` class?

https://github.com/markteekman/accessible-astro-components/blob/172738653da3b6bfb092c3e2875fa8326eb63bd7/Modal.astro#L186

That fixes the issue in Safari where the Modal isn't really showing because of that set height 🤔 

<img width="1012" alt="Scherm­afbeelding 2023-10-14 om 13 26 41" src="https://github.com/markteekman/accessible-astro-components/assets/3909046/70f4dfd2-35ae-4c51-be57-27c3912b8d11">

2023-10-16 09:29 UTC, david-abell commented
That's definitely busted but you are right, removing the 100% height fixes it. 

I also found some style problems that I hadn't resolved Friday. I was going to put another pull request together once I had it sorted. I can put them all here or still file another pull. Do you have a preference?

The issues I found:
 - specificity was making it harder than necessary to override white background/black text defaults. Using `:where(.modal)` seems to resolve this. 
 - dialog open/close transitions are broken (not the `.close-button:hover`). A keyframe animation works for on-open but close needs some javascript to add/remove a class. I can add the close animation if you'd like but I'm not sure if its necessary.

I think that's it if I haven't forgotten something else over the weekend...

There's also a typescript problem with astro 3 defaults and the card component but I'll leave that out here.

2023-10-17 17:38 UTC, markteekman commented
@david-abell thanks! And nice finds. There's no harm putting them in this PR I guess, it's related to the Modal anyways 😄

2023-10-18 07:56 UTC, david-abell commented
Sounds good. Should be all set now.

:heavy_check_mark: Remove `height: 100%` on .modal__inner for Safari. Works on my phone Safari 16.4 now.
:heavy_check_mark: Replace dialog fade-in transition with keyframe animation.
:heavy_check_mark: Lower style specificity. 
 - This also fixes upper corner radius showing as white when background-color is dark by having only one element with background color assigned.
 -  Root style sheet like in accessible-astro-starter still need the below added for overrides like dark mode to work. 
```css
      dialog {
        color: var(--font-color);
        background-color: var(--background);
      }
```

2023-10-22 11:44 UTC, markteekman approved these changes

2023-10-22 11:45 UTC, markteekman commented
Awesome @david-abell! Thank you for you invaluable contributions to this project 😊

2023-10-22 11:45 UTC, merged