Refactor accordion so it uses details/summary API
markteekman/accessible-astro-components pull request #78
Opened 2024-01-24 22:29 UTC by gsi-kevincarrera

2024-01-26 11:31 UTC, markteekman commented
Thanks for your contribution again @gsi-kevincarrera! I'll take a look at it soon 😄

2024-01-26 13:43 UTC, gsi-kevincarrera commented
Willing to get your feedback here :)

2024-02-03 09:08 UTC, markteekman commented
@gsi-kevincarrera thanks again for taking the time to look at this! I've got a couple of concerns before we can merge this to main, especially since it's a breaking change with AccordionItem.astro being deleted and refactoring of existing themes is needed if anyone updates to the latest version of the package. Currently there's a big difference in the look and feel of the 'old' vs the new accordions:

**Old** (general design)
<img width="563" alt="Scherm­afbeelding 2024-02-03 om 09 52 02" src="https://github.com/markteekman/accessible-astro-components/assets/3909046/69d86b37-ad9f-4967-b1d4-4f69f6fe7536">

**New** (general design)
<img width="550" alt="Scherm­afbeelding 2024-02-03 om 09 52 18" src="https://github.com/markteekman/accessible-astro-components/assets/3909046/27bb0743-670a-4745-949b-5ede9bdf5da2">

**Old** (focus outline)
<img width="560" alt="Scherm­afbeelding 2024-02-03 om 09 52 40" src="https://github.com/markteekman/accessible-astro-components/assets/3909046/b63cf9c9-2239-449f-8f28-082086818638">

**New** (focus outline)
<img width="538" alt="Scherm­afbeelding 2024-02-03 om 09 52 29" src="https://github.com/markteekman/accessible-astro-components/assets/3909046/d4bfc563-72af-4ae8-a893-d6d75b2707ec">

Some other concerns I had:
- In your style tag you use the `is:global` directive, this causes the styles to be applied multiple times when an accordion item is on the page. I think we can leave it out. 
- For the classes, all the components use [BEM](https://getbem.com/introduction/) so these should be renamed to `accordion-container` and `plus-icon`. 
- The `name` attirbute on `details` is currently not supported by Firefox, but can we a progressive enhancement. I would just name the prop `name` though. 
- All components need to support TypeScript, so you need to have an interface that defines the prop types
- All components need to use `rem` instead of `px` units
- It would be preferable to keep Accordion.astro as well as AccordionItem.astro so we can prevent breaking changes to themes updating to the latest version.

I think if we tackle these issues and make sure the component looks the same then we are there 🙂

2024-02-03 09:10 UTC, markteekman requested changes

2024-02-03 09:10 UTC, markteekman commented on Accordion.astro
> +
Last line can be removed

2024-02-03 09:10 UTC, markteekman commented on Accordion.astro
> +  @keyframes details-show {
Keyframes may be placed at the bottom

2024-02-03 09:10 UTC, markteekman commented on Accordion.astro
> +    list-style-type: none;
It's not a list item so you can remove this

2024-02-04 05:22 UTC, gsi-kevincarrera commented
Thanks for your time, I will be working in all of them, i ll come back soon

2024-04-22 07:19 UTC, markteekman commented
@gsi-kevincarrera how's it going, need any help with this? 🙂

2024-04-22 13:46 UTC, gsi-kevincarrera commented
Sorry,  I've been really busy, but thanks for the reminder 😅 I'm going to make time to finish the task

2024-04-22 15:34 UTC, markteekman commented
No worries Kevin and no rush! Was just checking whether you still wanted to do this, take your time 😊

2024-11-23 13:13 UTC, markteekman commented
Hey @gsi-kevincarrera, this PR has gone a little stale, which is okay, but since I've got a couple of changes I'm going to make to this project I'll have to close this PR down. I do want to thank you for the time you've invested in this 😃

2024-11-23 13:13 UTC, closed without merging

2024-11-23 13:25 UTC, gsi-kevincarrera commented
> Hey @gsi-kevincarrera, this PR has gone a little stale, which is okay, but since I've got a couple of changes I'm going to make to this project I'll have to close this PR down. I do want to thank you for the time you've invested in this 😃 

I do really want to apologize for not being able to complete it. It's been a tough year, with a lot on my plate, thank you

2024-11-23 21:02 UTC, markteekman commented
gsi-kevincarrera there's truly no need to apologize, no worries 🙂